### ISSUE TITLE
Development/Compiling/Self-hosting instructions

### ISSUE THREAD

**Issue by duyfken** [cofob/fastside#10]
To make it easier for people to create a standalone fastside instance.

Comparable to https://github.com/benbusby/farside?tab=readme-ov-file#development

**Comment by cofob** [comment]
Hello! I made small note about self-hosting in README (cbafd289234053ce551b990f080a191e0102c90c).
If there is a desire to write a full-fledged documentation on self-hosting - I will be glad to accept it)
