### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by Whoopee4954** [cofob/fastside#19]
Yesterday there were problems with redirecting. Today it seems that server is down :c

**Comment by cofob** [comment]
Hi.

As I can see - everything is working fine.

Could you please clarify a few things:
1. Are you from Russia?
RKN blocked the direct IP address of the server a long time ago, and recently blocked the whole cloudflare, so without a proxy you can't access fastside from Russia. Use I2P/Tor/Yggdrasil.
2. What domain are you using? (fastsi.de/cdn.fastside.link/etc).
3. What error does your browser give you?

**Comment by Whoopee4954** [comment]
> Hi.
> 
> As I can see - everything is working fine.
> 
> Could you please clarify a few things:
> 
> 1. Are you accessing fastside from Russia?
>    RKN blocked the direct IP address of the server a long time ago, and recently blocked the whole cloudflare, so without a proxy you can't access fastside from Russia. Use proxy or I2P/Tor/Yggdrasil mirrors.

Nope, not from Russia.

> 2. What domain are you using? (fastsi.de/cdn.fastside.link/etc).

Fastsi.de

> 3. What error does your browser give you?

Just that it couldn't resolve IP.

Today it works fine. Can access the main site and redirecting works.

P. S. Thank you for this project, it really works way faster than farside and it doesn't redirect to dead redirectors unlike farside.
