### ISSUE TITLE
Redlib redirects to Skyview/HyperPipe randomly

### ISSUE THREAD

**Issue by leonghui** [cofob/fastside#9]
Firstly, many thanks for providing this service!

I noticed today that `https://fastsi.de/redlib/` redirects to `https://skyview.social/` or `https://hyperpipe.surge.sh/` randomly instead of one of the libreddit instances. Is this a bug?

**Comment by cofob** [comment]
Hi. Can you check for the bug now please?

**Comment by leonghui** [comment]
Works great, thanks for the quick fix!
